export const CHRONIK_SUPPORT_COINS = ['xec', 'xpi', 'bch', 'xrg'];
export const CHRONIK_MODULE_OPTIONS = 'CHRONIK_MODULE_OPTIONS';
export const CHRONIK_CLIENTS = 'CHRONIK_CLIENTS';
export const CHRONIK_CLIENT_NODES = 'CHRONIK_CLIENT_NODES';
